sudo: required

language: node_js
node_js:
    - "12"

services:
  - docker

before_script:
  # Remove the local, Travis-generated "node_modules" directory, because when
  # we run the linters and tests, the local directory will be mounted into the
  # container and its "node_modules" directory would override the one we want
  # used, which is the one located at the root-level of the container.
  - rm -rf node_modules
  # Move TravisCI's checkout of kumascript into a submodule of kuma
  - cd ..
  - git clone https://github.com/mdn/kuma --depth 2
  - cd kuma
  - git submodule update --init locale
  - rmdir kumascript
  - mv ../kumascript .
  # Build the kumascript image
  - make build-kumascript
  # Run remaining tasks from the kumascript submodule
  - cd kumascript
script:
  - make lint
  - make lint-json
  - make test

notifications:
  email:
    - rjohnson@mozilla.com
